# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoccerStar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoccerStar
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'	
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'

  target 'SoccerStarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoccerStarUITests' do
    # Pods for testing
  end

end
